name: StarWars app CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    # Select Ubuntu runner.
    # Runners are the machines that execute jobs in a GitHub Actions workflow
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Enable KVM to make Ubuntu runner cheaper and faster
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0
          target: 'android-34'
          ndk: 'latest'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

#      - name: Run unit tests
#        run: ./gradlew test

#      - name: Run integration tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedCheck

#      - name: Run screenshot tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          target: google_apis
#          arch: x86_64
#          profile: Nexus 6
#          script: ./gradlew updateDebugScreenshotTest

#      - name: Upload test results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-results
#          path: app/build/reports/tests/testDebugUnitTest/

      - name: Run screenshot tests
        run: ./gradlew validateDebugScreenshotTest

      - name: List files in build directory
        run: find app/build/ -type f

      - name: Upload screenshot test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-test-results
          path: app/build/outputs/screenshotTest-results/
